### PR TITLE
`@trace` while and control flow tutorial

### LINKED ISSUE #1238: Traced while
realized we didn't have this. Since traced for becomes a while anyways I imagine this isn't that bad

### LINKED ISSUE #1317: malformed for loop assignment
Seeing an error when adding `@trace`, the function to reproduce is this
```julia
function temp(h::AbstractMatrix,η::AbstractMatrix,H::AbstractMatrix)
    m,n = size(h)
    @boundscheck (m,n) == size(η) || throw(BoundsError())
    @boundscheck (m,n) == size(H) || throw(BoundsError())

    @inbounds @trace for i in eachindex(η)
        h[i] = η[i] + H[i]
    end
end
```
and you don't even need to call the function, just trying to define it is enough to give the error. The specific message I see is
```
ERROR: LoadError: malformed for loop assignment
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] trace_for(mod::Module, expr::Expr; track_numbers::Type)
   @ ReactantCore ~/.julia/packages/ReactantCore/XJSZ9/src/ReactantCore.jl:173
 [3] var"@trace"(__source__::LineNumberNode, __module__::Module, args::Vararg{Any})
   @ ReactantCore ~/.julia/packages/ReactantCore/XJSZ9/src/ReactantCore.jl:160
in expression starting at REPL[6]:6
```

### PR DESCRIPTION
**Pull request by Pangoraw**
`@trace for` is now implemented with `@trace while`

Closes #1238 
Closes #1317

### CODE REVIEW

File: test/control_flow.jl [hunk 1]
```diff
@@ -653,6 +653,38 @@ end
     @test x.c ≈ x_ra.c
 end
 
+function for_eachindex(s, x)
+    for i in eachindex(x)
```
Comment (avik-pal) [inline test/control_flow.jl]: missing a `@trace` or was it intentional?

Comment (Pangoraw) [reply test/control_flow.jl]: good catch, thanks!

File: docs/src/tutorials/control-flow.md [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+```
+
+We can confirm by compiling our function and noticing that the result does not
+depend on the argument provided to the compiled function.
+
+```julia
+x = Reactant.ConcreteRArray(randn(Float32, 100))
+
+maybe_square_compiled = @compile maybe_square(true, x)
+maybe_square_compiled(false, x) == maybe_square_compiled(true, x)
```
Comment (wsmoses) [inline docs/src/tutorials/control-flow.md:35]: Showing code_hlo here would also be good

File: docs/src/tutorials/control-flow.md [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+    end
+    return x
+end
+```
+
+## Data-dependent Control Flow using [`@trace`](@ref)
+
+During tracing the arrays contain no data and only information about their shape
+and data type. As such, it is not possible to execute conditions that would
+depend on the value of an array. For this cases, ReactantCore provides the
```
Comment (wsmoses) [inline docs/src/tutorials/control-flow.md]: For these cases*

File: docs/src/tutorials/control-flow.md [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+[`@trace`](@ref) macro to allow capturing control flow expressions in the
+compiled program.
+
+Taking our same function from before and adding the [`@trace`](@ref) macro
+before the if expression will allow our compiled function to contain the
+condition.
+
+```@example control_flow_tutorial
+using Reactant
+
```
Comment (wsmoses) [inline docs/src/tutorials/control-flow.md:82]: I’m not sure this example is what you want fully — since if the cond is a regular and not concrete book it’s still baked into the function

Comment (wsmoses) [reply docs/src/tutorials/control-flow.md:82]: Ah I see it later — we should also explain the semantics of partially evaluating non concrete numbers

File: lib/ReactantCore/src/ReactantCore.jl
Comment (giordano) [inline lib/ReactantCore/src/ReactantCore.jl:1]: I have the feeling this broke GB-25, running the code is timing out now: https://github.com/PRONTOLab/GB-25/actions/runs/15510926515/job/43671788978.  Only difference I see compared to previous successful jobs is upgrade of ReactantCore
