### PR TITLE
feat: distributed + fix codegen

### LINKED ISSUE #992: Distributed Broadcast Compile Error
```julia
using Reactant, MPI

MPI.Init()

Reactant.Distributed.initialize()

mesh=Sharding.Mesh(reshape(Reactant.devices(), 2, :), (:x, :y))

x_ra = Reactant.to_rarray(ones(4, 4); sharding=Sharding.NamedSharding(mesh, (:x, :y)))

y_ra = ConcreteRNumber(3.0);

@. rad2deg(x_ra / y_ra)
```

```
ERROR: LoadError: ERROR: LoadError: INVALID_ARGUMENT: Invalid memory kind: unpinned_host; available memory kinds: unpinned_host

Stacktrace:
 [1] reactant_err(msg::Cstring)
   @ Reactant.XLA ~/reactant/Reactant.jl/src/xla/Utils.jl:12
 [2] Reactant.XLA.IFRT.Array(client::Reactant.XLA.IFRT.Client, array::Array{Float64, 0}, sharding::Reactant.XLA.IFRT.Sharding)
   @ Reactant.XLA.IFRT ~/reactant/Reactant.jl/src/xla/IFRT/Array.jl:39
 [3] macro expansion
   @ ~/reactant/Reactant.jl/src/Compiler.jl:1518 [inlined]
 [4] (::Reactant.Compiler.Thunk{Base.Broadcast.BroadcastFunction{Base.Broadcast.var"#11#12"{typeof(rad2deg), Tuple{Base.Broadcast.var"#13#14"{typeof(/), Tuple{Base.Broadcast.Pick{1}, Base.Broadcast.Pick{2}}}}}}, Symbol("##Base.Broadcast.BroadcastFunction(Base.Broadcast.var\"#11#12\"{typeof(rad2deg), Tuple{Base.Broadcast.var\"#13#14\"{typeof(/), Tuple{Base.Broadcast.Pick{1}, Base.Broadcast.Pick{2}}}}}(rad2deg, (Base.Broadcast.var\"#13#14\"{typeof(/), Tuple{Base.Broadcast.Pick{1}, Base.Broadcast.Pick{2}}}(/, (Base.Broadcast.Pick{1}(), Base.Broadcast.Pick{2}())),)))_reactant#235"), Tuple{ConcreteIFRTArray{Float64, 2, Reactant.Sharding.ShardInfo{Reactant.Sharding.HloSharding{2, 2}, Vector{Tuple{UnitRange{Int64}, UnitRange{Int64}}}}}, ConcreteIFRTNumber{Float64, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, true, Reactant.XLA.IFRT.LoadedExecutable, Nothing})(::ConcreteIFRTArray{Float64, 2, Reactant.Sharding.ShardInfo{Reactant.Sharding.HloSharding{2, 2}, Vector{Tuple{UnitRange{Int64}, UnitRange{Int64}}}}}, ::ConcreteIFRTNumber{Float64, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}})
   @ Reactant.Compiler ~/reactant/Reactant.jl/src/Compiler.jl:2042
 [5] copy(bc::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{ConcreteIFRTArray}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(rad2deg), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{ConcreteIFRTArray}, Nothing, typeof(/), Tuple{ConcreteIFRTArray{Float64, 2, Reactant.Sharding.ShardInfo{Reactant.Sharding.HloSharding{2, 2}, Vector{Tuple{UnitRange{Int64}, UnitRange{Int64}}}}}, ConcreteIFRTNumber{Float64, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}}}})
   @ Reactant ~/reactant/Reactant.jl/src/ConcreteRArray.jl:388
 [6] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{ConcreteIFRTArray}, Nothing, typeof(rad2deg), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{ConcreteIFRTArray}, Nothing, typeof(/), Tuple{ConcreteIFRTArray{Float64, 2, Reactant.Sharding.ShardInfo{Reactant.Sharding.HloSharding{2, 2}, Vector{Tuple{UnitRange{Int64}, UnitRange{Int64}}}}}, ConcreteIFRTNumber{Float64, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}}}})
   @ Base.Broadcast ./broadcast.jl:872
 [7] top-level scope
   @ ~/reactant/GB-25/sharding/simple_distributed_bcast.jl:13
in expression starting at /home/avik-pal/reactant/GB-25/sharding/simple_distributed_bcast.jl:13
INVALID_ARGUMENT: Invalid memory kind: unpinned_host; available memory kinds: 

Stacktrace:
 [1] reactant_err(msg::Cstring)
   @ Reactant.XLA ~/reactant/Reactant.jl/src/xla/Utils.jl:12
```

### LINKED ISSUE #993: IFRT: Incorrect Codegen for Resharded Inputs

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Review by wsmoses — APPROVED** [review]

**Comment by avik-pal** [comment]
I am using this branch to test oceananigans distributed. I will hold off merging till everything there is passing

**Comment by wsmoses** [comment]
ack

File: src/mlir/IR/Pass.jl
Comment (giordano) [inline src/mlir/IR/Pass.jl:1]: Can we quickly get this change as a separate PR?  That'd help a lot with https://github.com/PRONTOLab/GB-25/issue/67, see https://github.com/PRONTOLab/GB-25/pull/95

File: src/mlir/IR/Pass.jl [hunk 1]
```diff
@@ -76,6 +76,12 @@ function run!(pm::PassManager, mod::Module)
         API.mlirPassManagerRun(pm, mod)
     end)
     if isfailure(status)
+        dir = mktempdir()
+        path = joinpath(dir, "module.mlir")
+        io = open(path, "w")
+        println(io, repr(mod))
```
Comment (giordano) [inline src/mlir/IR/Pass.jl:82]: Based on the experience in https://github.com/PRONTOLab/GB-25/pull/36, you don't really want to convert that to a string.

Comment (wsmoses) [reply src/mlir/IR/Pass.jl:82]: also useful, writing the pass pipeline which was run

File: src/mlir/IR/Pass.jl [hunk 2]
```diff
@@ -79,7 +79,7 @@ function run!(pm::PassManager, mod::Module)
         dir = mktempdir()
         path = joinpath(dir, "module.mlir")
         io = open(path, "w")
-        println(io, repr(mod))
+        show(IOContext(io, :debug => true), mod)
```
Comment (avik-pal) [inline src/mlir/IR/Pass.jl:82]: @giordano add this as well to the other PR to print the debug info which would be useful to have?

File: src/Ops.jl [hunk 3]
```diff
@@ -133,6 +133,12 @@ end
     end
 end
 
+@noinline function constant(
+    x::Array{TracedRNumber{T},N}; location=mlir_stacktrace("constant", @__FILE__, @__LINE__)
+) where {T,N}
+    return reshape(vcat(x...), size(x)...; location)
+end
```
Comment (giordano) [inline src/Ops.jl:140]: Can you add this to #964 instead, to disentangle unrelated changes?

**Review by wsmoses — APPROVED** [review]
