### PR TITLE
`div` for ConcreteRNumber

### LINKED ISSUE #2673: Arithmetics for `ConcretePJRTNumber` missing? / Or `@trace` over `ConcretePJRTNumber` fails
I encountered the issue that `@trace` tries to divide a `ConcretePJRTNumber` when they are limits of the for loops, but `div` isn't implemented for `ConcretePJRTNumber` 

```Julia 
using Reactant 
# --- MWE 1: Minimal reproduction ---
div(1, ConcretePJRTNumber(10), RoundingMode{:ToZero}())

# --- MWE 2: @trace for outside @jit with ConcretePJRTNumber (SpeedyWeather pattern) ---
println("\n=== MWE 2: @trace for with Clock ===")

mutable struct Clock{I,S}
    timestep_counter::I
    n_timesteps::I
    sum::S
end

function time_stepping!(clock::Clock)
    @trace for _ in clock.timestep_counter:clock.n_timesteps
        clock.sum .+= 1
    end
    return nothing
end

clock = Reactant.to_rarray(Clock(1, 10, zeros(1)); track_numbers = true)

# Called OUTSIDE @jit, matching SpeedyWeather's run! -> time_stepping! path
@jit time_stepping!(clock)
```

### PR DESCRIPTION
**Pull request by maximilian-gelbrecht**
Fixes #2673

### CODE REVIEW

File: test/core/math_ops.jl [hunk 1]
```diff
@@ -248,6 +248,12 @@ end
     @test @jit(/(2, ConcreteRNumber(Int32(4)))) ≈ 0.5
 end
 
+@testset "div" begin
+    @test @jit(div(ConcreteRNumber(7), ConcreteRNumber(3))) == div(7, 3)
+    @test @jit(div(ConcreteRNumber(7), 3)) == div(7, 3)
+    @test @jit(div(7, ConcreteRNumber(3))) == div(7, 3)
```
Comment (Pangoraw) [inline test/core/math_ops.jl]: using `@jit` does not test the method you implemented (it goes through tracing and then XLA)
```suggestion
    @test div(ConcreteRNumber(7), ConcreteRNumber(3)) == div(7, 3)
    @test div(ConcreteRNumber(7), 3) == div(7, 3)
    @test div(7, ConcreteRNumber(3)) == div(7, 3)
```

File: src/ConcreteRArray.jl [hunk 2]
```diff
@@ -227,6 +227,12 @@ for jlop in (
     end
 end
 
+for T in (AbstractConcreteNumber, AbstractConcreteArray{<:Number,0})
+    @eval Base.div(x::$(T), y::$(T), r::RoundingMode=RoundToZero) = div(to_number(x), to_number(y), r)
+    @eval Base.div(x::$(T), y::Number, r::RoundingMode=RoundToZero) = div(to_number(x), y, r)
+    @eval Base.div(x::Number, y::$(T), r::RoundingMode=RoundToZero) = div(x, to_number(y), r)
```
Comment (Pangoraw) [inline src/ConcreteRArray.jl]: can you also add the MethodError ones from above:


```suggestion
    @eval Base.div(x::Number, y::$(T), r::RoundingMode=RoundToZero) = div(x, to_number(y), r)

    Base.div(x::$(T), y::TracedRNumber, r::RoundingMode=RoundToZero) = throw(MethodError(jlop, (x, y)))
    Base.div(x::TracedRNumber, y::$(T), r::RoundingMode=RoundToZero) = throw(MethodError(jlop, (x, y)))
```

File: src/ConcreteRArray.jl [hunk 3]
```diff
@@ -227,6 +227,18 @@ for jlop in (
...
+for T in (AbstractConcreteNumber, AbstractConcreteArray{<:Number,0})
+    @eval Base.div(x::$(T), y::$(T), r::RoundingMode=RoundToZero) =
+        div(to_number(x), to_number(y), r)
+    @eval Base.div(x::$(T), y::Number, r::RoundingMode=RoundToZero) =
+        div(to_number(x), y, r)
+    @eval Base.div(x::Number, y::$(T), r::RoundingMode=RoundToZero) =
+        div(x, to_number(y), r)
+
+    Base.div(x::$(T), y::TracedRNumber, r::RoundingMode=RoundToZero) = throw(MethodError(jlop, (x, y)))
+    Base.div(x::TracedRNumber, y::$(T), r::RoundingMode=RoundToZero) = throw(MethodError(jlop, (x, y)))
```
Comment (Pangoraw) [inline src/ConcreteRArray.jl]: Missed that sorry
```suggestion
    Base.div(x::$(T), y::TracedRNumber, r::RoundingMode=RoundToZero) = throw(MethodError(Base.div, (x, y)))
    Base.div(x::TracedRNumber, y::$(T), r::RoundingMode=RoundToZero) = throw(MethodError(Base.div, (x, y)))
```

Comment (maximilian-gelbrecht) [reply src/ConcreteRArray.jl]: Ah yes, true. Thank you for the suggestions!

File: src/ConcreteRArray.jl [hunk 4]
```diff
@@ -227,6 +227,22 @@ for jlop in (
...
+        div(to_number(x), y, r)
+    @eval Base.div(x::Number, y::$(T), r::RoundingMode=RoundToZero) =
+        div(x, to_number(y), r)
+
+    function Base.div(x::$(T), y::TracedRNumber, r::RoundingMode=RoundToZero)
+        throw(MethodError(Base.div, (x, y)))
+    end
+    function Base.div(x::TracedRNumber, y::$(T), r::RoundingMode=RoundToZero)
+        throw(MethodError(Base.div, (x, y)))
+    end
```
Comment (Pangoraw) [inline src/ConcreteRArray.jl]:
```suggestion
    @eval function Base.div(x::$(T), y::TracedRNumber, r::RoundingMode=RoundToZero)
        throw(MethodError(Base.div, (x, y)))
    end
    @eval function Base.div(x::TracedRNumber, y::$(T), r::RoundingMode=RoundToZero)
        throw(MethodError(Base.div, (x, y)))
    end
```

File: src/ConcreteRArray.jl [hunk 5]
```diff
@@ -227,6 +227,22 @@ for jlop in (
...
 
+for T in (AbstractConcreteNumber, AbstractConcreteArray{<:Number,0})
+    @eval Base.div(x::$(T), y::$(T), r::RoundingMode=RoundToZero) =
+        div(to_number(x), to_number(y), r)
+    @eval Base.div(x::$(T), y::Number, r::RoundingMode=RoundToZero) =
+        div(to_number(x), y, r)
+    @eval Base.div(x::Number, y::$(T), r::RoundingMode=RoundToZero) =
+        div(x, to_number(y), r)
+
+    @eval function Base.div(x::$(T), y::TracedRNumber, r::RoundingMode=RoundToZero)
```
Comment (wsmoses) [inline src/ConcreteRArray.jl]: this shouldn't be needed

Comment (Pangoraw) [reply src/ConcreteRArray.jl]: we hit this by removing:

```
Ambiguity #3
div(x::Number, y::Reactant.AbstractConcreteArray{<:Number, 0}) @ Reactant ~/work/Reactant.jl/Reactant.jl/src/ConcreteRArray.jl:235
div(lhs::Reactant.TracedRNumber{T}, rhs) where T @ Reactant.TracedRNumberOverrides ~/work/Reactant.jl/Reactant.jl/src/TracedRNumber.jl:331

Possible fix, define
  div(::Reactant.TracedRNumber{T}, ::Reactant.AbstractConcreteArray{<:Number, 0}) where T

Comment (wsmoses) [reply src/ConcreteRArray.jl]: ah, okay in that case we should then do to_number for the concretenumber input

Comment (Pangoraw) [reply src/ConcreteRArray.jl]: ok done

**Comment by maximilian-gelbrecht** [comment]
Is there still a problem with this? Anything I can help with?

**Comment by maximilian-gelbrecht** [comment]
The CI errors seem unrelated, do any other issues persist that keep this from merging?

**Comment by maximilian-gelbrecht** [comment]
I don't know your policies yet on PR approvals. Can I merge this now, or should I wait?

**Comment by maximilian-gelbrecht** [comment]
@wsmoses Can we merge this?
