### PR TITLE
traced control flow fixes

### LINKED ISSUE #793: Unexpected non-boolean (Reactant.TracedRNumber{Bool}) used in boolean context
I'm getting a `TypeError` when I don't expect to (if I am using `@trace` correctly). Here the code:

```julia
using Reactant

mutable struct TestClock{I}
    iteration :: I
end

mutable struct TestSimulation{C, I, B}
    clock :: C
    stop_iteration :: I
    running :: B
end

function test_run!(sim)
    while sim.running
        @trace if sim.clock.iteration >= sim.stop_iteration
            sim.running = false
        else
            sim.clock.iteration += 1 # time step
        end
    end
    return nothing
end

clock = TestClock(ConcreteRNumber(0))
simulation = TestSimulation(clock, 3, true)

r_run! = @compile sync=true test_run!(simulation)
r_run!(simulation)
```

```julia
julia> include("mwe.jl")
ERROR: LoadError: TypeError: non-boolean (Reactant.TracedRNumber{Bool}) used in boolean context
Stacktrace:
  [1] macro expansion
    @ ~/.julia/packages/ReactantCore/t40zc/src/ReactantCore.jl:378 [inlined]
  [2] test_run!
    @ ~/Projects/Reactant.jl/mwe.jl:15 [inlined]
  [3] test_run!(none::TestSimulation{TestClock{Reactant.TracedRNumber{Int64}}, Int64, Bool})
    @ Reactant ./<missing>:0
  [4] getproperty
    @ ./Base.jl:37 [inlined]
  [5] test_run!
    @ ~/Projects/Reactant.jl/mwe.jl:14 [inlined]
  [6] call_with_reactant(::typeof(test_run!), ::TestSimulation{TestClock{Reactant.TracedRNumber{Int64}}, Int64, Bool})
    @ Reactant ~/Projects/Reactant.jl/src/utils.jl:0
  [7] make_mlir_fn(f::Function, args::Tuple{TestSimulation{…}}, kwargs::Tuple{}, name::String, concretein::Bool; toscalar::Bool, return_dialect::Symbol, args_in_result::Symbol, construct_function_without_args::Bool, do_transpose::Bool)
    @ Reactant.TracedUtils ~/Projects/Reactant.jl/src/TracedUtils.jl:261
  [8] make_mlir_fn
    @ ~/Projects/Reactant.jl/src/TracedUtils.jl:153 [inlined]
  [9] compile_mlir!(mod::Reactant.MLIR.IR.Module, f::Function, args::Tuple{TestSimulation{…}}, callcache::Dict{Vector, @NamedTuple{…}}; optimize::Bool, no_nan::Bool, backend::String)
    @ Reactant.Compiler ~/Projects/Reactant.jl/src/Compiler.jl:600
 [10] compile_mlir! (repeats 2 times)
    @ ~/Projects/Reactant.jl/src/Compiler.jl:575 [inlined]
 [11] compile_xla(f::Function, args::Tuple{TestSimulation{TestClock{ConcreteRNumber{Int64, 1, Reactant.Sharding.ShardInfo{…}}}, Int64, Bool}}; client::Nothing, kwargs::@Kwargs{no_nan::Bool, optimize::Bool})
    @ Reactant.Compiler ~/Projects/Reactant.jl/src/Compiler.jl:1450
 [12] compile_xla
    @ ~/Projects/Reactant.jl/src/Compiler.jl:1429 [inlined]
 [13] compile(f::Function, args::Tuple{TestSimulation{TestClock{ConcreteRNumber{Int64, 1, Reactant.Sharding.ShardInfo{…}}}, Int64, Bool}}; sync::Bool, kwargs::@Kwargs{client::Nothing, no_nan::Bool, optimize::Bool})
    @ Reactant.Compiler ~/Projects/Reactant.jl/src/Compiler.jl:1493
 [14] top-level scope
    @ ~/Projects/Reactant.jl/src/Compiler.jl:1013
 [15] include(fname::String)
    @ Base.MainInclude ./client.jl:494
 [16] top-level scope
    @ REPL[2]:1
in expression starting at /Users/gregorywagner/Projects/Reactant.jl/mwe.jl:27
Some type information was truncated. Use `show(err)` to see complete types.
```

I'm also wondering whether `stop_iteration` and/or `running` also need to be `ConcreteRNumber`. Changing them so does not fix this error though.

### PR DESCRIPTION
**Pull request by jumerckx**
fixed 2 bugs:
* args and results in traced_if weren't accessed through their full path
* TracedToConcrete should be applied element per element such that traced_type isn't applied on the abstract vector eltype.

~**Marked as a draft for now because I commented out some wrong code but I think it should instead be replaced with right code...**~

The MWE from https://github.com/EnzymeAD/Reactant.jl/issues/793
becomes:
```julia
using Reactant
using Reactant.ReactantCore

mutable struct TestClock{I}
    iteration :: I
end

mutable struct TestSimulation{C, I, B}
    clock :: C
    stop_iteration :: I
    running :: B
end

function step!(sim)
    cond = sim.clock.iteration >= sim.stop_iteration
    @trace if cond
        sim.running = false
    else
        sim.clock.iteration += 1 # time step
    end
    return sim # note, this function returns sim which is used as an argument for the next while-loop iteration.
end

function test_run!(sim)
    ReactantCore.traced_while(sim->sim.running, step!, (sim, ))
end

clock = TestClock(ConcreteRNumber(0))
simulation = TestSimulation(clock, ConcreteRNumber(3), ConcreteRNumber(true))
# @code_hlo optimize=false test_run!(simulation)

r_run! = @compile sync=true test_run!(simulation)
r_run!(simulation)

```

Fix #793.

### CODE REVIEW

**Comment by jumerckx** [comment]
CI shows this is wrong:`TracedToConcrete should be applied element per element such that traced_type isn't applied on the abstract vector eltype.` :(

**Comment by giordano** [comment]
Would this fix also #768?

@jumerckx Side note, when you open a pull request it'd be best to [link it to the issue it's solving](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue), for example by using one of the [keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) which do that automatically. I edited your message to this already for this pull request.

**Comment by jumerckx** [comment]
> Would this fix also https://github.com/EnzymeAD/Reactant.jl/issues/768?

No. To be sure, `@trace if` should best be used with a single-variable condition.
The fix is to the transformation from
```
@trace if expr(...)
```
to
```
cond = expr(...)
@trace if cond
```
in the macro definition, but I haven't looked at this yet, and am a bit preoccupied so would wait with this as it's not too critical (?).

> @jumerckx Side note, when you open a pull request it'd be best to [link it to the issue it's solving](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue), for example by using one of the [keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) which do that automatically. I edited your message to this already for this pull request.

Right, I didn't want to add autoclose to an issue that isn't mine but will do so in the future if it's a clear fix like this one, thanks!

**Comment by jumerckx** [comment]
CI failure looks unrelated to my changes?

**Comment by jumerckx** [comment]
This pr should be good but should maybe get a quick review, still? Probably from @avik-pal, @Pangoraw, or @wsmoses?

**Review by wsmoses — COMMENTED** [review]
looks reasonable to me, but can one of @Pangoraw and/or @avik-pal review this before merging (since they are more experts on this sort of thing)

**Comment by Pangoraw** [comment]
I am not too familiar with this part of the code (and tracing in general) so letting this for @avik-pal to review.

File: src/Ops.jl [hunk 1]
```diff
@@ -2058,15 +2091,28 @@ end
         end
     end
 
+    results = map(x -> x.value, MLIR.IR.results(if_compiled))
```
Comment (avik-pal) [inline src/Ops.jl:2094]: seems unused?

**Review by avik-pal — APPROVED** [review]
looks good to me

File: src/Ops.jl (hunk 1 above)
Comment (jumerckx) [reply src/Ops.jl:2094]: Thanks!

File: test/control_flow.jl [hunk 2]
```diff
@@ -736,3 +737,40 @@ end
...
+
+mutable struct TestSimulation{C,I,B}
+    clock::C
+    stop_iteration::I
+    running::B
+end
+
+function step!(sim)
+    cond = sim.clock.iteration >= sim.stop_iteration
+    @trace if cond
```
Comment (wsmoses) [inline test/control_flow.jl:753]: @jumerckx in a follow up can we add a test here with

```
@trace if a > b
```

Comment (jumerckx) [reply test/control_flow.jl:753]: That's not fixed by this pr, though (https://github.com/EnzymeAD/Reactant.jl/pull/794#issuecomment-2676781794)

Comment (wsmoses) [reply test/control_flow.jl:753]: ah yeah fair, okay understood. We can wait for @glwagner to see if it's too difficult to rewrite the conditions throughout oceananigans and get back to this then

Comment (glwagner) [reply test/control_flow.jl:753]: I can't think of a situation in which this rewrite would not be possible. The main issue is just a potential loss of productivity since its a bit of a gotcha
