### PR TITLE
Specialize transpose! and adjoint! for AnyTracedRMatrix

### LINKED ISSUE #1611: copy of transpose fails due to scalar indexing
Sometimes I need a non-lazy transpose, e.g. to change data layout in memory depending on the access patterns used by some algorithms. I tried copy of a lazy-transposed array, but that currently runs into scalar indexing trouble (same with `collect` instead of `copy`:

```
julia> using Reactant; Reactant.set_default_backend("cpu")

julia> A = rand(Float32, 100, 10); rA = Reactant.to_rarray(A);

julia> foo(A) = copy(transpose(A))
foo (generic function with 1 method)

julia> typeof(foo(A))
Matrix{Float32} (alias for Array{Float32, 2})

julia> @code_hlo foo(rA)
ERROR: Scalar indexing is disallowed.
Invocation of getindex(::TracedRArray, ::Vararg{Int, N}) resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore should be avoided.

If you want to allow scalar iteration, use `allowscalar` or `@allowscalar`
to enable scalar iteration globally or for the operations in question.
Stacktrace:
  [1] error
    @ ./error.jl:35 [inlined]
  [2] (::Nothing)(none::typeof(error), none::String)
    @ Reactant ./<missing>:0
  [3] ErrorException
    @ ./boot.jl:323 [inlined]
  [4] error
    @ ./error.jl:35 [inlined]
  [5] call_with_reactant(::Reactant.MustThrowError, ::typeof(error), ::String)
    @ Reactant /user/.julia/packages/Reactant/gBXlB/src/utils.jl:0
[...]
```

This works, though:

```julia
julia> function bar(A)
           A_transposed = transpose(A)
           B = similar(A_transposed)
           B .= A_transposed
       end

julia> typeof(bar(A))
Matrix{Float32} (alias for Array{Float32, 2})

julia> @code_hlo bar(rA)
module @reactant_bar attributes {mhlo.num_partitions = 1 : i64, mhlo.num_replicas = 1 : i64} {
  func.func @main(%arg0: tensor<10x100xf32>) -> tensor<100x10xf32> {
    %0 = stablehlo.transpose %arg0, dims = [1, 0] : (tensor<10x100xf32>) -> tensor<100x10xf32>
    return %0 : tensor<100x10xf32>
  }
}
```

### PR DESCRIPTION
**Pull request by oschulz**
Fixes #1611

@wsmoses where should tests for this go?

### CODE REVIEW

**Comment by avik-pal** [comment]
`test/integration/linear_algebra.jl`

**Comment by oschulz** [comment]
Thanks @avik-pal!

I added the tests.

**Comment by oschulz** [comment]
Good to merge, @avik-pal ?

File: src/stdlibs/LinearAlgebra.jl [hunk 1]
```diff
@@ -81,7 +81,7 @@ for (AT, comp) in ((:LowerTriangular, "GE"), (:UpperTriangular, "LE"))
             px = materialize_traced_array(parent(x))
             row_idxs = @opcall iota(Int, [m, n]; iota_dimension=1)
             col_idxs = @opcall iota(Int, [m, n]; iota_dimension=2)
-            indicator = @opcall compare(row_idxs, col_idxs; comparison_direction=$(comp))
+            indicator = @opcall compare(row_idxs, col_idxs; comparison_direction=($(comp)))
```
Comment (avik-pal) [inline src/stdlibs/LinearAlgebra.jl]:
```suggestion
            indicator = @opcall compare(row_idxs, col_idxs; comparison_direction=$(comp))
```

File: src/stdlibs/LinearAlgebra.jl [hunk 2]
```diff
@@ -606,7 +612,7 @@ function LinearAlgebra.lu(A::AnyTracedRArray{T,2}, ::RowMaximum; kwargs...) wher
     return lu!(copy(A), RowMaximum(); kwargs...)
 end
 function LinearAlgebra.lu(
-    A::AnyTracedRArray{T,N}, ::RowMaximum=RowMaximum(); kwargs...
+    A::AnyTracedRArray{T,N}, (::RowMaximum)=RowMaximum(); kwargs...
```
Comment (avik-pal) [inline src/stdlibs/LinearAlgebra.jl]:
```suggestion
    A::AnyTracedRArray{T,N}, ::RowMaximum=RowMaximum(); kwargs...
```

File: src/stdlibs/LinearAlgebra.jl [hunk 3]
```diff
@@ -170,9 +170,11 @@ for (AT, dcomp, ocomp) in (
         m, n = size(x)
         row_idxs = @opcall iota(Int, [m, n]; iota_dimension=1)
         col_idxs = @opcall iota(Int, [m, n]; iota_dimension=2)
-        data_indicator = @opcall compare(row_idxs, col_idxs; comparison_direction=$(dcomp))
+        data_indicator = @opcall compare(
+            row_idxs, col_idxs; comparison_direction=($(dcomp))
+        )
```
Comment (avik-pal) [inline src/stdlibs/LinearAlgebra.jl]:
```suggestion
        data_indicator = @opcall compare(row_idxs, col_idxs; comparison_direction=$(dcomp))
```

File: src/stdlibs/LinearAlgebra.jl [hunk 4]
```diff
@@ -170,9 +170,11 @@ for (AT, dcomp, ocomp) in (
...
         original_indicator = @opcall compare(
-            row_idxs, col_idxs; comparison_direction=$(ocomp)
+            row_idxs, col_idxs; comparison_direction=($(ocomp))
```
Comment (avik-pal) [inline src/stdlibs/LinearAlgebra.jl]:
```suggestion
            row_idxs, col_idxs; comparison_direction=$(ocomp)
```

**Comment by avik-pal** [comment]
test failures are unrelated.

@wsmoses  do you know what this is?

https://github.com/EnzymeAD/Reactant.jl/actions/runs/17463707754/job/49594263477?pr=1621#step:11:1525

```julia
Failed to precompile EnzymeCoreExt [c3ed20f3-746d-5a71-99a7-df1cca8c2b90] to "/home/runner/.julia/compiled/v1.10/EnzymeCoreExt/jl_aSA4HK".
julia: /home/runner/work/Reactant.jl/Reactant.jl/julia/src/gc.c:1289: jl_gc_pool_alloc_inner: Assertion `jl_atomic_load_relaxed(&ptls->gc_state) == 0' failed.
```

**Comment by oschulz** [comment]
@avik-pal when should JuliaFormatter be used (for which files in Reactant) currently?

**Comment by wsmoses** [comment]
No I don't know what's up there

**Comment by avik-pal** [comment]
> @avik-pal when should JuliaFormatter be used (for which files in Reactant) currently?

pin JuliaFormatter to v1. v2 introduces quite a few strange formatting qwirks

**Comment by oschulz** [comment]
> pin JuliaFormatter to v1. v2 introduces quite a few strange formatting qwirks

Thanks!
