### PR TITLE
Fix FFTW plans that are wrapped

### LINKED ISSUE #2158: FFT Planning Issue in Reactant 0.2.2+
I am trying to use `ReverseWithPrimal` to take a gradient of a Breeze model while using the latest version of Reactant. I run into an error :
```julia
using Breeze
using CUDA
using Enzyme
using Oceananigans.Architectures: CPU, GPU, ReactantState
using Oceananigans.Units
using Reactant
using Statistics

function check_breeze_derivative()
    try
        """
        Construct a moderately resolved 2D×1 RectilinearGrid suitable for dry
        thermal bubble experiments. The `architecture` argument is currently
        unused but kept to make CPU/GPU switching trivial.
        """
        function make_grid(architecture)
            grid = RectilinearGrid(architecture; size = (8, 8), halo = (5, 5),
                                   x = (-10e3, 10e3), z = (0, 10e3),
                                   topology = (Periodic, Flat, Bounded))
            return grid
        end

        """
        Build an AtmosphereModel with high-order WENO advection.
        """
        function make_model(grid)
            model = AtmosphereModel(grid; advection=WENO(order=9))
            return model
        end

        """
        Populate a perturbation potential-temperature field shaped like a
        circular bubble that sits atop the ambient stratification.
        """
        function make_initial_condition(model)
            r₀ = 2e3
            Δθ = 10 # K
            N² = 1e-6
            θ₀ = model.dynamics.reference_state.potential_temperature
            g = model.thermodynamic_constants.gravitational_acceleration

            """
            Pointwise initializer for the thermal bubble: exponential background
            stratification plus a compact perturbation with radius `r₀`.
            """
            @inline function θ_init_function(x, z;
                        x₀ = mean(xnodes(model.grid, Center())),
                        z₀ = 0.3*model.grid.Lz,
                        N² = N²)

                θ̄ = θ₀ * exp(N² * z / g)
                r = sqrt((x - x₀)^2 + (z - z₀)^2)
                θ′ = Δθ * max(0, 1 - r / r₀)

                return θ̄ + θ′
            end

            θ = Field{Center, Nothing, Center}(model.grid)
            set!(θ, θ_init_function)

            return θ
        end

        """
        Reset the model state, rewind the clock, and advance `nsteps` using the
        last adaptive time step size stored on the clock.
        """
        function run_model!(model, θᵢ, nsteps)
            set!(model, θ = θᵢ)        

            model.clock.iteration = 0
            model.clock.time = 0

            Δt = model.clock.last_Δt
            @trace mincut = true checkpointing = true track_numbers = false for i = 1:nsteps
                time_step!(model, Δt)
            end

            return nothing
        end

        """
        Convenience wrapper that advances the model and returns the domain mean
        temperature squared, used as the scalar loss for differentiation.
        """
        function loss_function(model, θᵢ, nsteps)
            run_model!(model, θᵢ, nsteps)        
            return mean(model.temperature^2)
        end
        
        """
        Differentiate `loss_function` with respect to the initial condition
        field using Enzyme's reverse-mode API.
        """
        function grad_loss_function(model, θᵢ, dθᵢ, nsteps)
            mode = set_strong_zero(Enzyme.ReverseWithPrimal)
            grad, loss = autodiff(mode,
                               loss_function, 
                               Active,
                               Const(model),
                               Duplicated(θᵢ, dθᵢ),
                               Const(nsteps))

            return grad, loss
        end

        # setup the model
        # architecture = ReactantState()
        architecture = CPU()
        grid = @time "make_grid" make_grid(architecture)
        model = @time "make_model" make_model(grid)
        θᵢ = @time "make_initial_condition" make_initial_condition(model)

        # differentiate the loss function
        nsteps = Reactant.ConcreteRNumber(10) # number of time steps to run the model for
        dθᵢ = Field{Center, Nothing, Center}(model.grid) # need to allocate here, as copy() doesn't work correctly for Field
        r_dloss_dθᵢ = @time "compile" @compile raise_first=true raise=true sync=true grad_loss_function(model, θᵢ, dθᵢ, nsteps)
        grad, loss_value = @time "r_dloss_dθᵢ" r_dloss_dθᵢ(model, θᵢ, dθᵢ, nsteps)
        println("grad: ", grad)
        println("loss_value: ", loss_value)
    catch e
        @error "Error in check_breeze_derivative." exception=(e, catch_backtrace())
    end

    nothing
end

check_breeze_derivative()
```
ERROR:
```julia
include("test/test_ad.jl")
make_grid: 0.000072 seconds (156 allocations: 7.266 KiB)
make_model: 0.160017 seconds (295.37 k allocations: 16.419 MiB, 99.14% compilation time)
make_initial_condition: 0.096522 seconds (351.76 k allocations: 17.888 MiB, 99.60% compilation time)
┌ Error: Error in check_breeze_derivative.
│   exception =
│    AssertionError: Could not recursively make tracer of object of type Oceananigans.Solvers.DiscreteTransform{FFTW.cFFTWPlan{ComplexF64, -1, true, 3, Tuple{Int64}}, Oceananigans.Solvers.Forward, RectilinearGrid{Float64, Periodic, Flat, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Float64, Float64}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Nothing, CPU}, Int64, Periodic, Int64, Nothing, Nothing} into Oceananigans.Solvers.DiscreteTransform{FFTW.cFFTWPlan{ComplexF64, -1, true, 3, Tuple{Int64}}, Oceananigans.Solvers.Forward, RectilinearGrid{Float64, Periodic, Flat, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Float64, Float64}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Nothing, CPU}, Int64, Periodic, Int64, Nothing, Nothing} at field 1 (named plan), need object of type FFTW.cFFTWPlan{ComplexF64, -1, true, 3, Tuple{Int64}} found object of type ReactantAbstractFFTsExt.ReactantFFTInPlacePlan{ComplexF64, Tuple{Int64}}
```
Seems to be a variation on the FFT problems seen and resolved here: #1926 
Also see: #2095

### PR DESCRIPTION
**Pull request by ptiede**
Attempts to fix #2158 

I don't fully understand what `traced_type_inner` actually does, and if what I did is `legal`. The MWE in the issue now passes though...

I also don't really like the implementation... but hey it is a start

@wsmoses @avik-pal @giordano

### CODE REVIEW

File: ext/ReactantAbstractFFTsExt.jl [hunk 1]
```diff
@@ -77,17 +110,17 @@ for op in (:rfft, :fft, :ifft)
     @eval $(plan_name){T}(dims) where {T} = $(plan_name){T,typeof(dims)}(dims)
 
     @eval function AbstractFFTs.$(plan_f)(
-        x::Reactant.AnyTracedRArray{T}, dims=1:ndims(x)
+        x::Reactant.TracedRArray{T}, dims=1:ndims(x)
```
Comment (wsmoses) [inline ext/ReactantAbstractFFTsExt.jl]: Let's not revert the any

Comment (ptiede) [reply ext/ReactantAbstractFFTsExt.jl]: Ahhhhhhhh stupid local copy

**Comment by wsmoses** [comment]
Traced type inner should just return the type of make tracer, but without the object, just acting on types

**Comment by ptiede** [comment]
> Traced type inner should just return the type of make tracer, but without the object, just acting on types

Ok, good, that is what I figured. I just couldn't make a really clean implementation of this because I need to handle the conversion from the bfft to ifft which is such a shame.

File: ext/ReactantAbstractFFTsExt.jl [hunk 2]
```diff
@@ -2,24 +2,86 @@ module ReactantAbstractFFTsExt
...
+    @nospecialize(prev::AbstractFFTs.Plan{T}),
+    @nospecialize(path),
+    mode;
+    @nospecialize(track_numbers::Type = Union{}),
+    @nospecialize(sharding = Reactant.Sharding.NoSharding()),
+    @nospecialize(runtime),
+    kwargs...,
 ) where {T}
-    return reactant_fftplan(prev)
+    RT = Reactant.traced_type(typeof(prev), Val(mode), track_numbers, sharding, runtime)
```
Comment (wsmoses) [inline ext/ReactantAbstractFFTsExt.jl:21]: if the new type you added has a relevant constructor, you can just forward to https://github.com/EnzymeAD/Reactant.jl/blob/232ea41c48e052f58936af133467b920012a42e5/src/Tracing.jl#L1036 which should do some of the setup for you without issue

File: ext/ReactantFFTWExt.jl [hunk 3]
```diff
@@ -16,34 +16,57 @@ const AFTEx = Base.get_extension(Reactant, :ReactantAbstractFFTsExt)
...
+end
+
+function AFTEx.make_reactant_fftplan(plan::FFTW.rFFTWPlan{T,BACKWARD}) where {T}
     osz = AbstractFFTs.brfft_output_size(size(plan), AFTEx.reallength(plan), fftdims(plan)) # just to make sure it is defined
     nrm = AFTEx.normbfft(real(T), osz, fftdims(plan))
     return AFTEx.ReactantIRFFTPlan{T}(fftdims(plan), AFTEx.reallength(plan)) * nrm
 end
 
-end
+end
```
Comment (giordano) [inline ext/ReactantFFTWExt.jl]:
```suggestion
end

```

File: ext/ReactantAbstractFFTsExt.jl (hunk 2 above)
Comment (ptiede) [reply ext/ReactantAbstractFFTsExt.jl:21]: Looking at this doesn't the new type have to have the same number of fields as the original?

Comment (wsmoses) [reply ext/ReactantAbstractFFTsExt.jl:21]: ah is that not the case here [didn't look too closely], if not we don't need to use

Comment (ptiede) [reply ext/ReactantAbstractFFTsExt.jl:21]: Sadly no :(

**Comment by ptiede** [comment]
I'm not sure what some of the failures are from. Also, the formatting seems weird? It says certain files aren't formatted that I didn't touch in this PR.
