### PR TITLE
fix: aliasing of results with buffers set later

### LINKED ISSUE #1289: Duplicating Scalars for Optimisers prevents CSE
The learning rates are duplicated for each parameter which means we will have a bazzillion `broadcast_in_dim`s in the IR and those cant be CSEd

### PR DESCRIPTION
**Pull request by avik-pal**
fixes https://github.com/LuxDL/Lux.jl/issues/1289

### CODE REVIEW

File: test/integration/optimisers.jl [hunk 1]
```diff
@@ -12,3 +12,12 @@ is_empty_buffer(x::ConcretePJRTNumber) = any(x === C_NULL for x in x.data)
     @test !is_empty_buffer(opt_state[2].rule.eta)
     @test !is_empty_buffer(opt_state[3].rule.eta)
 end
+
+@testset "Correct Aliasing" begin
+    ps = (a = rand(4), b = rand(2)) |> Reactant.to_rarray
```
Comment (wsmoses) [inline test/integration/optimisers.jl:17]: lgtm but for ease can we come up with a smaller test that would error (just to make future debugging of the result cache code easier)

**Review by wsmoses — APPROVED** [review]
