### PR TITLE
fix: vararg compilation

### LINKED ISSUE #293: compilation failure of getindex with a type-assert
```julia
julia> x = Reactant.to_rarray(rand(2))
2-element ConcreteRArray{Float64, 1}:
 0.2325602477968195
 0.2510465242325195

julia> @allowscalar x[1]
0.2325602477968195

julia> @allowscalar x[1:1]
ERROR: TypeError: in typeassert, expected Tuple{Int64}, got a value of type Int64
Stacktrace:
  [1] (::Reactant.var"#277#287"{Bool, Bool, typeof(Reactant.mysetindex!), Tuple{ConcreteRArray{…}, Float64, Int64}, Vector{Union{…}}, Tuple{Reactant.TracedRArray{…}, Float64, Int64}})()
    @ Reactant /mnt/software/lux/Reactant.jl/src/utils.jl:157
  [2] block!(f::Reactant.var"#277#287"{Bool, Bool, typeof(Reactant.mysetindex!), Tuple{ConcreteRArray{…}, Float64, Int64}, Vector{Union{…}}, Tuple{Reactant.TracedRArray{…}, Float64, Int64}}, blk::Reactant.MLIR.IR.Block)
    @ Reactant.MLIR.IR /mnt/software/lux/Reactant.jl/src/mlir/IR/Block.jl:201
  [3] make_mlir_fn(f::Function, args::Tuple{…}, kwargs::Tuple{}, name::String, concretein::Bool; toscalar::Bool, return_dialect::Symbol, no_args_in_result::Bool, construct_function_without_args::Bool, do_transpose::Bool)
    @ Reactant /mnt/software/lux/Reactant.jl/src/utils.jl:120
  [4] make_mlir_fn
    @ /mnt/software/lux/Reactant.jl/src/utils.jl:40 [inlined]
  [5] #10
    @ /mnt/software/lux/Reactant.jl/src/Compiler.jl:283 [inlined]
  [6] block!(f::Reactant.Compiler.var"#10#15"{typeof(Reactant.mysetindex!), Tuple{ConcreteRArray{Float64, 1}, Float64, Int64}}, blk::Reactant.MLIR.IR.Block)
    @ Reactant.MLIR.IR /mnt/software/lux/Reactant.jl/src/mlir/IR/Block.jl:201
  [7] #9
    @ /mnt/software/lux/Reactant.jl/src/Compiler.jl:282 [inlined]
  [8] mmodule!(f::Reactant.Compiler.var"#9#14"{Reactant.MLIR.IR.Module, typeof(Reactant.mysetindex!), Tuple{ConcreteRArray{Float64, 1}, Float64, Int64}}, blk::Reactant.MLIR.IR.Module)
    @ Reactant.MLIR.IR /mnt/software/lux/Reactant.jl/src/mlir/IR/Module.jl:92
  [9] compile_mlir!(mod::Reactant.MLIR.IR.Module, f::Function, args::Tuple{ConcreteRArray{Float64, 1}, Float64, Int64}; optimize::Bool)
    @ Reactant.Compiler /mnt/software/lux/Reactant.jl/src/Compiler.jl:279
 [10] compile_mlir!
    @ /mnt/software/lux/Reactant.jl/src/Compiler.jl:278 [inlined]
 [11] (::Reactant.Compiler.var"#34#36"{Bool, typeof(Reactant.mysetindex!), Tuple{ConcreteRArray{Float64, 1}, Float64, Int64}})()
    @ Reactant.Compiler /mnt/software/lux/Reactant.jl/src/Compiler.jl:686
 [12] context!(f::Reactant.Compiler.var"#34#36"{Bool, typeof(Reactant.mysetindex!), Tuple{ConcreteRArray{Float64, 1}, Float64, Int64}}, ctx::Reactant.MLIR.IR.Context)
    @ Reactant.MLIR.IR /mnt/software/lux/Reactant.jl/src/mlir/IR/Context.jl:76
 [13] compile_xla(f::Function, args::Tuple{ConcreteRArray{Float64, 1}, Float64, Int64}; client::Nothing, optimize::Bool)
    @ Reactant.Compiler /mnt/software/lux/Reactant.jl/src/Compiler.jl:683
 [14] compile_xla
    @ /mnt/software/lux/Reactant.jl/src/Compiler.jl:678 [inlined]
 [15] compile(f::Function, args::Tuple{ConcreteRArray{Float64, 1}, Float64, Int64}; client::Nothing, optimize::Bool, sync::Bool)
    @ Reactant.Compiler /mnt/software/lux/Reactant.jl/src/Compiler.jl:710
 [16] compile
    @ /mnt/software/lux/Reactant.jl/src/Compiler.jl:709 [inlined]
 [17] setindex!(a::ConcreteRArray{Float64, 1}, v::Float64, args::Int64)
    @ Reactant /mnt/software/lux/Reactant.jl/src/ConcreteRArray.jl:262
 [18] macro expansion
    @ ./multidimensional.jl:940 [inlined]
 [19] macro expansion
    @ ./cartesian.jl:64 [inlined]
 [20] _unsafe_getindex!
    @ ./multidimensional.jl:938 [inlined]
 [21] _unsafe_getindex(::IndexCartesian, A::ConcreteRArray{Float64, 1}, I::UnitRange{Int64})
    @ Base ./multidimensional.jl:929
 [22] _getindex
    @ ./multidimensional.jl:915 [inlined]
 [23] getindex(A::ConcreteRArray{Float64, 1}, I::UnitRange{Int64})
    @ Base ./abstractarray.jl:1312
 [24] top-level scope
    @ /mnt/.julia/packages/GPUArraysCore/GMsgk/src/GPUArraysCore.jl:210
 [25] top-level scope
    @ none:1
Some type information was truncated. Use `show(err)` to see complete types.
```

I have seen this at quite a few places but this is the minimal one I could produce

### PR DESCRIPTION
**Pull request by avik-pal**
fixes #293

### CODE REVIEW

**Review by wsmoses — APPROVED** [review]

File: test/compile.jl [hunk 1]
```diff
@@ -81,3 +81,11 @@ end
     x_ra = Reactant.to_rarray(true; track_numbers=(Number,))
     @test @jit(iszero(x_ra)) == false
 end
+
+@testset "Vararg compilation: Issue #293" begin
+    x = rand(2, 2)
+    x_ra = Reactant.to_rarray(x)
+
+    @test @allowscalar(x_ra[1]) ≈ x[1]
+    @test @allowscalar(x_ra[1:1]) ≈ x[1:1]
```
Comment (mofeing) [inline test/compile.jl:90]: @avik-pal mmm no function is being compiled here right? how do you test it then?

Comment (avik-pal) [reply test/compile.jl:90]: That's intentional, the ConcreteArray getindex for non-integers will fallback to setindex via compile `mysetindex!`

Comment (mofeing) [reply test/compile.jl:90]: ah oki
