### PR TITLE
fix: empty buffers

### LINKED ISSUE #861: Empty buffers with `Optimisers.setup`
```julia
using Optimisers, Reactant

opt = Descent(Reactant.to_rarray(0.1; track_numbers=Number))

x = Reactant.to_rarray((rand(3), rand(2), rand(2)))

opt_state = @jit Optimisers.setup(opt, x)
```

```julia
quote
    #= /mnt/software/lux/Reactant.jl/src/Compiler.jl:1639 =#
    usbuf_1 = (traced_getfield(getindex(args, 1), $(Expr(:quote, 1)))).data
    sbuf_1 = only(XLA.synced_buffer(usbuf_1))
    usbuf_2 = (traced_getfield(getindex(args, 2), $(Expr(:quote, 1)))).data
    sbuf_2 = only(XLA.synced_buffer(usbuf_2))
    usbuf_3 = (traced_getfield(getindex(args, 2), $(Expr(:quote, 2)))).data
    sbuf_3 = only(XLA.synced_buffer(usbuf_3))
    usbuf_4 = (traced_getfield(getindex(args, 2), $(Expr(:quote, 3)))).data
    sbuf_4 = only(XLA.synced_buffer(usbuf_4))
    #= /mnt/software/lux/Reactant.jl/src/Compiler.jl:1640 =#
    ()
    #= /mnt/software/lux/Reactant.jl/src/Compiler.jl:1641 =#
    ()
    #= /mnt/software/lux/Reactant.jl/src/Compiler.jl:1642 =#
    result = (%new(Optimisers.Leaf{Descent{ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, Nothing}, %new(Descent{ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, ConcretePJRTNumber{Float64}((Reactant.XLA.PJRT.AsyncBuffer(Reactant.XLA.PJRT.Buffer(Ptr{Nothing} @0x0000000000000000), nothing),))), $(Expr(:quote, nothing)), $(Expr(:quote, false))), %new(Optimisers.Leaf{Descent{ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, Nothing}, %new(Descent{ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, ConcretePJRTNumber{Float64}((Reactant.XLA.PJRT.AsyncBuffer(Reactant.XLA.PJRT.Buffer(Ptr{Nothing} @0x0000000000000000), nothing),))), $(Expr(:quote, nothing)), $(Expr(:quote, false))), %new(Optimisers.Leaf{Descent{ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, Nothing}, %new(Descent{ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, ConcretePJRTNumber{Float64}((Reactant.XLA.PJRT.AsyncBuffer(Reactant.XLA.PJRT.Buffer(Ptr{Nothing} @0x0000000000000000), nothing),))), $(Expr(:quote, nothing)), $(Expr(:quote, false))))
    (traced_getfield(traced_getfield(traced_getfield(result, $(Expr(:quote, 1))), $(Expr(:quote, 1))), $(Expr(:quote, 1)))).data = (traced_getfield(args[1], $(Expr(:quote, 1)))).data
    #= /mnt/software/lux/Reactant.jl/src/Compiler.jl:1643 =#
    return result
end
```

```
(Leaf(Descent(ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}(0.1)), nothing), Leaf(Descent(<Empty Buffer eltype ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}} of size ()>), nothing), Leaf(Descent(<Empty Buffer eltype ConcretePJRTNumber{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}} of size ()>), nothing))
```

### PR DESCRIPTION
**Pull request by avik-pal**
fixes #861

### CODE REVIEW

File: src/TracedUtils.jl [hunk 1]
```diff
@@ -300,7 +300,7 @@ function make_mlir_fn(
             seen_results,
             traced_args[i],
             concretein ? (:resargs, i) : (),
-            Reactant.TracedTrack;
+            Reactant.NoStopTracedTrack;
```
Comment (avik-pal) [inline src/TracedUtils.jl:303]: @wsmoses / @Pangoraw / @jumerckx why was this TracedTrack? Without a NoStop we wont set buffers where the output is repeated but set into different paths to the result

Comment (wsmoses) [reply src/TracedUtils.jl:303]: my guess is because this code predates NoStopTracedTrack and we didn't realize the issue.

In any case, can you add a quick test?
